// src/components/Layout.tsx
import React, { Component } from 'react'
import PropTypes from 'prop-types'
import { StaticQuery, graphql } from 'gatsby'
import styled, { createGlobalStyle } from 'styled-components'

import Header from './Header'
import '../styles/layout.css'

const GlobalStyle = createGlobalStyle`
  body {
    color: var(--primary-text);
    background-color: var(--body-background);
    transition: background-color 100ms ease-out, color 100ms ease-out;
  }
  a {
    color: var(--link-color);
  }
`

declare global {
  interface Window {
    __theme: string
    __onThemeChange: () => void
    __setPreferredTheme: (newTheme: string) => void
  }
}

const ThemeToggle = styled.button`
  position: fixed;
  right: 16px;
  bottom: 16px;
  margin: 0;
  border: none;
  color: var(--primary-text);
  background: var(--theme-button-background);
  padding: 4px 8px;
  border-radius: 4px;
`

class Layout extends Component {
  static propTypes = {
    children: PropTypes.node.isRequired,
  }

  state = {
    selectedTheme: 'light',
  }

  componentDidMount() {
    this.setState({ selectedTheme: window.__theme })
    window.__onThemeChange = () => {
      this.setState({ selectedTheme: window.__theme })
    }
  }

  toggleTheme = () => {
    window.__setPreferredTheme(
      this.state.selectedTheme === 'light' ? 'dark' : 'light'
    )
  }

  render() {
    return (
      <StaticQuery
        query={graphql`
          query SiteTitleQuery {
            site {
              siteMetadata {
                title
              }
            }
          }
        `}
        render={data => (
          <>
            <Header siteTitle={data.site.siteMetadata.title} />
            <div
              style={{
                margin: `0 auto`,
                maxWidth: 992,
                padding: `0px 16px 24px`,
                paddingTop: 0,
              }}
            >
              <main css="display: flex;flex-direction: column;">
                {this.props.children}
              </main>
              <footer>
                © {new Date().getFullYear()}, Built with
                {` `}
                <a href="https://www.gatsbyjs.org">Gatsby</a>
              </footer>
            </div>
            <ThemeToggle onClick={this.toggleTheme}>
              Go {this.state.selectedTheme === 'dark' ? 'Light' : 'Dark'}
            </ThemeToggle>
            <GlobalStyle />
          </>
        )}
      />
    )
  }
}

export default Layout

// src/routes/__layout.svelte
<script>
	import { onMount } from 'svelte'
	import Nav from '$lib/components/Nav.svelte'
	import '../app.scss'

	let selectedTheme = 'light'

	onMount(() => {
		selectedTheme = window.__theme || 'light'
	})

	function toggleTheme() {
		const newTheme = window.__theme === 'light' ? 'dark' : 'light'
		window.__setPreferredTheme(newTheme)
		selectedTheme = newTheme
	}

	export let segment
</script>

<Nav {segment} />

<main>
	<slot />
</main>

<button class="theme-toggle" on:click={toggleTheme}>
	Go {selectedTheme === 'dark' ? 'Light' : 'Dark'}
</button>

<style>
	main {
		position: relative;
		display: flex;
		flex-direction: column;
		margin: 0 auto;
		max-width: 992px;
		padding: 0 16px 24px;
	}

	button.theme-toggle {
		position: fixed;
		right: 16px;
		bottom: 16px;
		margin: 0;
		border: none;
		color: var(--primary-text);
		background: var(--theme-button-background);
		padding: 4px 8px;
		border-radius: 4px;
	}
</style>
