// src/components/ColorField.svelte
<script lang="ts">
	function handleChange(e: Event) {
		const newValue = (e.target as HTMLInputElement).value

		if (
			(Number(newValue) >= min && Number(newValue) <= max) ||
			(isHex && newValue.length <= 6)
		) {
			updateColor(newValue)
		}
	}

	function handleKeyDown(e: KeyboardEvent) {
		if (isHex) return

		if (e.code === 'ArrowUp' && value < max) {
			e.preventDefault()
			updateColor(Number(value) + 1)
		} else if (e.code === 'ArrowDown' && value > min) {
			e.preventDefault()
			updateColor(Number(value) - 1)
		}
	}

	export let identifier: string
	export let label: string
	export let value: ColorFieldInput = ''
	export let updateColor: (val: ColorFieldInput) => void
	export let min: number = undefined
	export let max: number = undefined
	export let prefix: string = undefined
	export let suffix: string = undefined
	export let size: number = 4
	export let isHex: boolean = false
</script>

<style>
	.container {
		position: relative;
		display: flex;
		height: 100%;
		flex-direction: column;
		justify-content: center;
		align-items: center;
	}

	.container:not(:last-of-type) {
		border-right: 1px solid var(--input-divider);
	}

	input {
		background: transparent;
		box-sizing: content-box;
		padding: 0 16px;
		font-size: 24px;
		color: var(--primary-text);
		text-align: center;
		text-transform: uppercase;
		outline: none;
		border: 0;
		border-bottom: 4px solid transparent;
		border-radius: inherit;
		transition: border-bottom-color 200ms ease-out;
	}

	input:focus {
		border-bottom-color: var(--focus-underline);
	}

	label {
		color: var(--input-inner-label);
		font-size: 14px;
		line-height: 22px;
	}

	.supplemental-text {
		position: absolute;
		bottom: 4px;
		font-size: 20px;
		color: var(--input-static-text);
	}

	.prefix {
		left: 8px;
	}

	.suffix {
		right: 8px;
	}
</style>

<div class="container">
	<label for={identifier}>{label}</label>
	{#if prefix}
		<span
			class="supplemental-text prefix"
			data-testid="color-prefix"
		>{prefix}</span>
	{/if}
	<input
		type="text"
		id={identifier}
		data-testid="color-field"
		{value}
		{size}
		on:input={handleChange}
		on:keydown={handleKeyDown}
	/>
	{#if suffix}
		<span
			class="supplemental-text suffix"
			data-testid="color-suffix"
		>{suffix}</span>
	{/if}
</div>

// src/components/ColorField.tsx
import React, { KeyboardEvent, ChangeEvent } from 'react'
import styled from 'styled-components'

const Container = styled.div`
  position: relative;
  display: flex;
  height: 100%;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  :not(:only-of-type):not(:last-of-type) {
    border-right: 1px solid var(--input-divider);
  }
`

const Input = styled.input`
  background: transparent;
  box-sizing: content-box;
  padding: 0 16px;
  font-size: 24px;
  color: var(--primary-text);
  text-align: center;
  text-transform: uppercase;
  outline: none;
  border: 0;
  border-bottom: 4px solid transparent;
  border-radius: inherit;
  transition: border-bottom-color 200ms ease-out;
  &:focus {
    border-bottom-color: var(--focus-underline);
  }
`

const InnerLabel = styled.label`
  color: var(--input-inner-label);
  font-size: 14px;
  line-height: 22px;
`

const SupplementalText = styled.span`
  position: absolute;
  font-size: 20px;
  color: var(--input-static-text);
`

type Props = {
  identifier: string
  isHex?: boolean
  label: string
  max?: number
  min?: number
  prefix?: string
  size?: number
  suffix?: string
  updateColor: (val: ColorFieldInput) => void
  value: ColorFieldInput
}

const ColorField = (props: Props) => {
  const {
    identifier,
    label,
    value = '',
    updateColor,
    min,
    max,
    prefix,
    suffix,
    size = 4,
    isHex = false,
  } = props

  function handleChange(e: ChangeEvent) {
    const newValue = (e.target as HTMLInputElement).value

    if (
      (Number(newValue) >= min && Number(newValue) <= max) ||
      (isHex && newValue.length <= 6)
    ) {
      updateColor(newValue)
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (isHex) return

    if (e.keyCode === 38 && value < max) {
      e.preventDefault()
      updateColor(Number(value) + 1)
    } else if (e.keyCode === 40 && value > min) {
      e.preventDefault()
      updateColor(Number(value) - 1)
    }
  }

  return (
    <Container>
      <InnerLabel htmlFor={identifier}>{label}</InnerLabel>
      {prefix && (
        <SupplementalText
          css="bottom: 4px;left: 8px;"
          data-testid="color-prefix"
        >
          {prefix}
        </SupplementalText>
      )}
      <Input
        id={identifier}
        data-testid="color-field"
        value={value}
        size={size}
        prefix={prefix}
        suffix={suffix}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
      />
      {suffix && (
        <SupplementalText
          css="bottom: 4px;right: 8px;"
          data-testid="color-suffix"
        >
          {suffix}
        </SupplementalText>
      )}
    </Container>
  )
}

export default ColorField
