// src/lib/components/ContrastStatus.svelte
<script lang="ts">
	export let isPass: boolean
</script>

<span class:pass={isPass} data-testid="contrast-item-status">{isPass ? 'PASS' : 'FAIL'}</span>

<style>
	span {
		width: 96px;
		text-align: center;
		padding: 8px 16px;
		border-radius: 24px;
		font-weight: 700;
		transition:
			color 150ms ease-in-out,
			background 150ms ease-in-out;
		will-change: color, background;
		background: var(--status-fail-background);
		color: var(--status-fail-foreground);
	}

	span.pass {
		background: var(--status-pass-background);
		color: var(--status-pass-foreground);
	}
</style>

// src/components/ContrastStatus.tsx
import React from 'react'
import styled from 'styled-components'

const Container = styled.span<{ isPass: boolean }>`
  width: 96px;
  text-align: center;
  padding: 8px 16px;
  border-radius: 24px;
  background: ${props =>
    props.isPass
      ? 'var(--status-pass-background)'
      : 'var(--status-fail-background)'};
  color: ${props =>
    props.isPass
      ? 'var(--status-pass-foreground)'
      : 'var(--status-fail-foreground)'};
  font-weight: 700;
  transition: color 150ms ease-in-out, background 150ms ease-in-out;
  will-change: color, background;
`

const ContrastStatus = ({ isPass }: Props) => {
  return (
    <Container isPass={isPass} data-testid="contrast-item-status">
      {isPass ? 'PASS' : 'FAIL'}
    </Container>
  )
}

type Props = {
  isPass: boolean
}

export default ContrastStatus
