// src/components/ColorSet.tsx
import React, { FormEvent } from 'react'
import styled from 'styled-components'

import Row from './Row'
import ColorField from './ColorField'
import media from '../styles/media'

const Form = styled.form`
  display: flex;
  flex-direction: column;

  ${media.desktop} {
    flex-direction: row;
    align-items: center;
  }

  :not(:last-child) {
    margin-bottom: 1.45rem;
  }
`

const Header = styled.h3`
  display: inline-block;
  margin-bottom: 0;
  margin-right: auto;
  margin-bottom: 16px;

  ${media.desktop} {
    margin-bottom: 0;
    margin-top: 1.45rem;
  }
`

const FieldsetWrapper = styled.div`
  display: flex;
  flex-wrap: wrap;
`

const Fieldset = styled.fieldset`
  display: inline-block;
  border: none;
  border-top: 1px solid var(--kebab-border);
  margin-bottom: 0;
  :not(:last-child) {
    margin-right: 16px;
  }
`

const Legend = styled.legend`
  padding: 4px 8px;
  color: var(--supplemental-text);
  font-size: 18px;
  width: auto;
  text-align: center;
`

const InputContainer = styled(Row)`
  border: 2px solid var(--input-border);
  border-radius: 6px;
  padding: 6px;
  background-color: var(--input-background);
  margin-bottom: 0;
`

const ColorSet = (props: Props) => {
  const {
    colors: { h, s, l, r, g, b, hex },
    header,
    updateColor,
    setIdentifier,
  } = props

  return (
    <Form
      onSubmit={(e: FormEvent) => e.preventDefault()}
      data-testid={`${header}-form`}
    >
      <Header>{header}</Header>
      <FieldsetWrapper>
        <Fieldset>
          <Legend>HSL</Legend>
          <InputContainer>
            <ColorField
              identifier={`${setIdentifier}-hue`}
              label="Hue"
              value={h}
              min={0}
              max={360}
              updateColor={val => updateColor('h', val)}
            />
            <ColorField
              identifier={`${setIdentifier}-saturation`}
              label="Saturation"
              min={0}
              max={100}
              value={s}
              suffix="%"
              updateColor={val => updateColor('s', val)}
            />
            <ColorField
              identifier={`${setIdentifier}-lightness`}
              label="Lightness"
              min={0}
              max={100}
              value={l}
              suffix="%"
              updateColor={val => updateColor('l', val)}
            />
          </InputContainer>
        </Fieldset>
        <Fieldset>
          <Legend>RGB</Legend>
          <InputContainer>
            <ColorField
              identifier={`${setIdentifier}-red`}
              label="Red"
              min={0}
              max={255}
              value={r}
              updateColor={val => updateColor('r', val)}
            />
            <ColorField
              identifier={`${setIdentifier}-green`}
              label="Green"
              min={0}
              max={255}
              value={g}
              updateColor={val => updateColor('g', val)}
            />
            <ColorField
              identifier={`${setIdentifier}-blue`}
              label="Blue"
              min={0}
              max={255}
              value={b}
              updateColor={val => updateColor('b', val)}
            />
          </InputContainer>
        </Fieldset>
        <Fieldset>
          <Legend>HEX</Legend>
          <InputContainer>
            <ColorField
              identifier={`${setIdentifier}-hex`}
              label="Hex"
              value={hex}
              updateColor={val => updateColor('hex', val)}
              prefix="#"
              size={8}
              isHex
            />
          </InputContainer>
        </Fieldset>
      </FieldsetWrapper>
    </Form>
  )
}

type Props = {
  colors: ColorSet
  header: string
  setIdentifier: string
  updateColor: (key: string, val: ColorFieldInput) => void
}

export default ColorSet

// src/lib/components/ColorSet.svelte
<script lang="ts">
	import ColorField from './ColorField.svelte'
	import ColorFieldset from './ColorFieldset.svelte'

	export let header: string
	export let colors: ColorSetType
	export let updateColor: (key: string, val: ColorFieldInput) => void
	export let setIdentifier: string

	$: ({ h, s, l, r, g, b, hex } = colors)
</script>

<form on:submit|preventDefault data-testid={`${header}-form`}>
	<h3>{header}</h3>
	<div class="wrapper">
		<ColorFieldset title="HSL">
			<ColorField
				identifier={`${setIdentifier}-hue`}
				label="Hue"
				value={h}
				min={0}
				max={360}
				updateColor={(val) => updateColor('h', val)}
			/>
			<ColorField
				identifier={`${setIdentifier}-saturation`}
				label="Saturation"
				value={s}
				min={0}
				max={100}
				suffix="%"
				updateColor={(val) => updateColor('s', val)}
			/>
			<ColorField
				identifier={`${setIdentifier}-lightness`}
				label="Lightness"
				value={l}
				min={0}
				max={100}
				suffix="%"
				updateColor={(val) => updateColor('l', val)}
			/>
		</ColorFieldset>

		<ColorFieldset title="RGB">
			<ColorField
				identifier={`${setIdentifier}-red`}
				label="Red"
				value={r}
				min={0}
				max={255}
				updateColor={(val) => updateColor('r', val)}
			/>
			<ColorField
				identifier={`${setIdentifier}-green`}
				label="Green"
				value={g}
				min={0}
				max={255}
				updateColor={(val) => updateColor('g', val)}
			/>
			<ColorField
				identifier={`${setIdentifier}-blue`}
				label="Blue"
				value={b}
				min={0}
				max={255}
				updateColor={(val) => updateColor('b', val)}
			/>
		</ColorFieldset>

		<ColorFieldset title="HEX">
			<ColorField
				identifier={`${setIdentifier}-hex`}
				label="Hex"
				value={hex}
				updateColor={(val) => updateColor('hex', val)}
				prefix="#"
				size={8}
				isHex
			/>
		</ColorFieldset>
	</div>
</form>

<style>
	form {
		display: flex;
		flex-direction: column;
	}

	form:not(:last-child) {
		margin-bottom: 1.45rem;
	}

	h3 {
		display: inline-block;
		margin-bottom: 0;
		margin-right: auto;
		margin-bottom: 16px;
	}

	.wrapper {
		display: flex;
		flex-wrap: wrap;
	}

	@media only screen and (min-width: 1024px) {
		form {
			flex-direction: row;
			align-items: center;
		}

		h3 {
			margin-bottom: 0;
			margin-top: 1.45rem;
		}
	}
</style>
