// src/components/ContrastItem.tsx
import React, { FunctionComponent } from 'react'
import styled from 'styled-components'

import Row from './Row'
import ContrastStatus from './ContrastStatus'

const LabelContainer = styled.div`
  display: flex;
  flex-direction: column;
  flex: 1;
`

const Label = styled.p`
  font-size: 18px;
  font-weight: 500;
  margin: 0;
  color: var(--primary-text);
`

const Subtext = styled.p`
  font-size: 16px;
  font-weight: 400;
  margin: 0;
  color: var(--supplemental-text);
`

type Props = {
  contrast: number
  label: string
  min: number
  subtext?: string
}

const ContrastItem: FunctionComponent<Props> = (props: Props) => {
  const { label, subtext, contrast, min } = props

  return (
    <Row css="align-items: center;margin: 8px 0;" data-testid="contrast-item">
      <LabelContainer>
        <Label>{label}</Label>
        {subtext && <Subtext data-testid="contrast-subtext">{subtext}</Subtext>}
      </LabelContainer>
      <ContrastStatus isPass={contrast >= min} />
    </Row>
  )
}

export default ContrastItem

// src/lib/components/ContrastItem.svelte
<script lang="ts">
	import ContrastStatus from './ContrastStatus.svelte'

	export let contrast: number
	export let label: string
	export let min: number
	export let subtext: string = undefined
</script>

<style>
	.wrapper {
		display: flex;
		align-items: center;
		margin: 8px 0;
	}

	.label {
		font-size: 18px;
		font-weight: 500;
		margin: 0;
		color: var(--primary-text);
	}

	.subtext {
		font-size: 16px;
		font-weight: 400;
		margin: 0;
		color: var(--supplemental-text);
	}

	.label-container {
		display: flex;
		flex-direction: column;
		flex: 1;
	}
</style>

<div class="wrapper" data-testid="contrast-item">
	<div class="label-container">
		<p class="label">{label}</p>
		{#if subtext}
			<p class="subtext" data-testid="contrast-subtext">{subtext}</p>
		{/if}
	</div>

	<ContrastStatus isPass={contrast >= min} />
</div>
